<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_All</name>
   <tag></tag>
   <elementGuidId>67b7ce11-ac92-4746-a058-da70f1869cd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SelectedBusinessUnitSiteAreaID_chosen']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SelectedBusinessUnitSiteAreaID_chosen > a.chosen-single</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SelectedBusinessUnitSiteAreaID_chosen a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd3909b6-bda5-48a0-be63-756ec29bc1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chosen-single</value>
      <webElementGuid>1f1e8648-fa49-48bf-9aea-fb57ece924f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>9eed01eb-3cb0-4382-9fbf-105604bacebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectedBusinessUnitSiteAreaID_chosen&quot;)/a[@class=&quot;chosen-single&quot;]</value>
      <webElementGuid>2ca28372-6fec-4630-ab39-f635bc2c3afa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SelectedBusinessUnitSiteAreaID_chosen']/a</value>
      <webElementGuid>07b91e89-5c12-44e1-8f4a-65073dc4d6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Unit Site Area'])[1]/following::a[1]</value>
      <webElementGuid>3d48bb8a-4937-4acf-bec2-fccf72aaa63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amandelbult'])[2]/following::a[1]</value>
      <webElementGuid>d854cc84-a412-49a5-b10f-0c6522ba081c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[6]/preceding::a[1]</value>
      <webElementGuid>169202f0-0a9a-47a5-9cf7-bfc08dee860a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/a</value>
      <webElementGuid>60cd5695-f2a2-4c90-ad19-82670db7c3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'All' or . = 'All')]</value>
      <webElementGuid>bb0145f8-b400-48dc-a380-4ce8fcf59731</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
