<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Equipment_arrow (1)</name>
   <tag></tag>
   <elementGuidId>be6bbeaa-3002-4264-999f-7b11a9f7234a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-equipment']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-equipment > a > i.arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Equipment&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0fb4b251-1631-494b-8e18-0a62ba5550fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow</value>
      <webElementGuid>a3e6d3f1-3ff3-4d0c-8901-8e27aeddf9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-equipment&quot;)/a[1]/i[@class=&quot;arrow&quot;]</value>
      <webElementGuid>d241b908-b463-4db7-a360-6747fb681846</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-equipment']/a/i</value>
      <webElementGuid>297ff0c9-4552-4525-a22a-97b08cfbda02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/i</value>
      <webElementGuid>22fd1fbf-e05d-47b0-b76e-c90ca4255e18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
