<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Equipment Type Reg Test Bulk Upload</name>
   <tag></tag>
   <elementGuidId>1faa076a-4fc4-4318-9509-fa4b2f027b58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SelectedEquipmentTypeID_chosen']/div/ul/li[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Equipment Type Reg Test Bulk Upload&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>15dab34e-92cc-4136-9557-53492b3a8fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active-result result-selected</value>
      <webElementGuid>29068598-2aeb-44e7-89cc-9722ab01ff29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-array-index</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>3a7e1b6d-068a-4f76-bde9-684f6ef6abd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Equipment Type Reg Test Bulk Upload</value>
      <webElementGuid>af80ea7b-22d4-4646-b548-7aaa769a358c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectedEquipmentTypeID_chosen&quot;)/div[@class=&quot;chosen-drop&quot;]/ul[@class=&quot;chosen-results&quot;]/li[@class=&quot;active-result result-selected&quot;]</value>
      <webElementGuid>7958b136-2fae-4eec-b8a9-ecd23a48e8e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SelectedEquipmentTypeID_chosen']/div/ul/li[9]</value>
      <webElementGuid>0bddd70a-ff26-404a-9eb1-0a2046cddb01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dump truck'])[2]/following::li[1]</value>
      <webElementGuid>796c5cab-15aa-4589-b08e-45306b2141a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BARGE SYSTEM TOOL'])[2]/following::li[2]</value>
      <webElementGuid>54455326-3ac0-4075-98de-e1f271e8bc9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Front end loader'])[2]/preceding::li[1]</value>
      <webElementGuid>218deae4-fcdd-405d-8d16-e396ec961c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bobcat'])[2]/preceding::li[2]</value>
      <webElementGuid>fb6de8e5-a8e8-4cd3-b9c0-d4ed14b2214c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]</value>
      <webElementGuid>7a8aeccb-daa2-4993-bbfd-e1a980786b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Equipment Type Reg Test Bulk Upload' or . = 'Equipment Type Reg Test Bulk Upload')]</value>
      <webElementGuid>2c5d12a3-5b86-4d27-971c-c49bffc8f341</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
